check process redis with pidfile /var/run/redis/redis.pid
  start program = "/usr/bin/redis-server /etc/redis.conf --daemonize yes --pidfile /var/run/redis/redis.pid --dir /data/redis --logfile /data/log/redis.log"
  stop  program = "/usr/bin/redis-cli shutdown"
  if failed host localhost port 6379 type TCP then restart
  if 3 restarts within 5 cycles then timeout
